### PR TITLE
Feature/migrate ut types

### PR DESCRIPTION
**Pull request by sbeitzel**
Fix issue #25 by switching to use `UTType` instead of `CFString` for attachment uploads, &c.

This also brings the build for the main application as well as all the dependencies up to macOS 13. I understand that this may not be desirable in the main project.

### CODE REVIEW

**Comment by sbeitzel** [comment]
I've moved the minimum macOS versions to 12.0.

**Review by chucker — APPROVED** [review]
lgtm

**Comment by chucker** [comment]
Broke between d09dce4f7a03fae9bfe02f8267bc66ce4d9999dd and 38c27ca3514afd2a594dcb052b66f79c05e01c41. Getting

```
2022-11-30 15:36:15.273381+0100 Mastonaut[70702:9139552] -[_UTCoreType isEqualToString:]: unrecognized selector sent to instance 0x1ef29c830
2022-11-30 15:36:15.273803+0100 Mastonaut[70702:9139552] [General] -[_UTCoreType isEqualToString:]: unrecognized selector sent to instance 0x1ef29c830
2022-11-30 15:36:15.277269+0100 Mastonaut[70702:9139552] [General] (
	0   CoreFoundation                      0x00000001937dc418 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x0000000193326ea8 objc_exception_throw + 60
	2   CoreFoundation                      0x000000019387ec3c -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00000001937426b0 ___forwarding___ + 1600
	4   CoreFoundation                      0x0000000193741fb0 _CF_forwarding_prep_0 + 96
	5   AppKit                              0x0000000196f99d8c +[NSPasteboard _typeIdentifierIskUTTypeFileURL:] + 40
	6   AppKit                              0x0000000196c47738 +[NSPasteboard _isValidPasteboardUTI:logStringMessage:] + 40
	7   AppKit                              0x0000000196f9af28 -[NSPasteboard readObjectsForClasses:options:] + 572
	8   CoreTootin                          0x00000001041eb274 $s10CoreTootin24AttachmentsSubcontrollerC03addC010pasteboardSbSo12NSPasteboardC_tF + 488
	9   Mastonaut                           0x00000001030cf284 $s9Mastonaut30StatusComposerWindowControllerC18readFromPasteboard3forSb10CoreTootin04BaseC8TextViewC_tF + 128
	10  Mastonaut                           0x00000001030cf33c $s9Mastonaut30StatusComposerWindowControllerC18readFromPasteboard3forSb10CoreTootin04BaseC8TextViewC_tFTo + 52
	11  Mastonaut                           0x00000001031c4a04 $s9Mastonaut16ComposerTextViewC5pasteyyypSgF + 156
	12  Mastonaut                           0x00000001031c4cc0 $s9Mastonaut16ComposerTextViewC5pasteyyypSgFTo + 144
	13  AppKit                              0x0000000196b612f0 -[NSApplication(NSResponder) sendAction:to:from:] + 440
	14  AppKit                              0x0000000196c2d998 -[NSMenuItem _corePerformAction] + 336
	15  AppKit                              0x0000000196c2d714 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 104
	16  AppKit                              0x0000000196f1eb7c -[NSMenu _performActionForItem:atIndex:fromEvent:] + 212
	17  AppKit                              0x0000000196c2cc24 -[NSMenu performKeyEquivalent:] + 356
	18  AppKit                              0x000000019705c090 routeKeyEquivalent + 428
	19  AppKit                              0x0000000196ae3ba0 -[NSApplication(NSEvent) sendEvent:] + 652
	20  AppKit                              0x0000000196d36144 -[NSApplication _handleEvent:] + 60
	21  AppKit                              0x00000001969abc14 -[NSApplication run] + 500
	22  AppKit                              0x0000000196983058 NSApplicationMain + 880
	23  Mastonaut                           0x0000000102f8b7c8 main + 44
	24  dyld                                0x0000000193357e50 start + 2544
)
```

**Comment by chucker** [comment]
So, this particular bug is fixed in `3922682d110aa7c8e043de128486606ba841e5de`, if you want to pull that.

(The issue is in https://developer.apple.com/documentation/appkit/nspasteboard/readingoptionkey/1530353-urlreadingcontentsconformtotypes — it expects a string array, not an UTI array. And it's evidently not very type-safe. :( )

**Pull request merged**
